/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vacancies */
        get: operations["get_vacancies_vacancies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vacancy */
        get: operations["get_vacancy_vacancies__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Adresa */
        Adresa: {
            /** Cislodomovni */
            cisloDomovni?: number | null;
            /** Cisloorientacni */
            cisloOrientacni?: string | null;
            /**
             * Dodatekadresy
             * @description Adresa - dodatek adresy
             */
            dodatekAdresy?: string | null;
            /** Kodadresnihomista */
            kodAdresnihoMista?: number | null;
            /** Psc */
            psc?: string | null;
            /** @description Adresa - typ domovního čísla, typ stavebního objektu */
            typCislaDomovniho?: components["schemas"]["TypCislaDomovniho"] | null;
            kraj?: components["schemas"]["Kraj"] | null;
            okres?: components["schemas"]["Okres"] | null;
            obec?: components["schemas"]["Obec"] | null;
            mestskyObvodMestskaCast?: components["schemas"]["MestskyObvodMestskaCast"] | null;
            mestskyObvodVPraze?: components["schemas"]["MestskyObvodVPraze"] | null;
            castObce?: components["schemas"]["CastObce"] | null;
            /** Nazevcastiobce */
            nazevCastiObce?: string | null;
            ulice?: components["schemas"]["Ulice"] | null;
        };
        /** Adresa1 */
        Adresa1: {
            /** Cislodomovni */
            cisloDomovni?: number | null;
            /** Cisloorientacni */
            cisloOrientacni?: string | null;
            /**
             * Dodatekadresy
             * @description Adresa - dodatek adresy
             */
            dodatekAdresy?: string | null;
            /** Kodadresnihomista */
            kodAdresnihoMista?: number | null;
            /** Psc */
            psc?: string | null;
            /** @description Adresa - typ domovního čísla, typ stavebního objektu */
            typCislaDomovniho?: components["schemas"]["TypCislaDomovniho"] | null;
            kraj?: components["schemas"]["Kraj"] | null;
            okres?: components["schemas"]["Okres"] | null;
            obec?: components["schemas"]["Obec"] | null;
            mestskyObvodMestskaCast?: components["schemas"]["MestskyObvodMestskaCast"] | null;
            mestskyObvodVPraze?: components["schemas"]["MestskyObvodVPraze"] | null;
            castObce?: components["schemas"]["CastObce"] | null;
            /** Nazevcastiobce */
            nazevCastiObce?: string | null;
            ulice?: components["schemas"]["Ulice"] | null;
        };
        /** CastObce */
        CastObce: {
            /** Id */
            id: string;
        };
        /** Dovednost */
        Dovednost: {
            /** Id */
            id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Jazyk */
        Jazyk: {
            /** Id */
            id: string;
        };
        /** KdeSeHlasit */
        KdeSeHlasit: {
            /**
             * Email
             * @description Kontaktovat zaměstnavatele e-mailem - e-mail
             */
            email?: string | null;
            /**
             * Telefon
             * @description Kontaktovat zaměstnavatele telefonem - telefon
             */
            telefon?: string | null;
            /**
             * Mistokontaktu
             * @description Kontaktovat zaměstnavatele osobně - místo kontaktu
             */
            mistoKontaktu?: string | null;
            /** @description Adresa kontaktu */
            adresa?: components["schemas"]["Adresa1"] | null;
        };
        /** KomuSeHlasit */
        KomuSeHlasit: {
            /**
             * Email
             * @description Kontaktovat zaměstnavatele e-mailem - e-mail
             */
            email?: string | null;
            /**
             * Telefon
             * @description Kontaktovat zaměstnavatele telefonem - telefon
             */
            telefon?: string | null;
            /**
             * Jmeno
             * @description Komu se hlásit - jméno kontaktní osoby
             */
            jmeno?: string | null;
            /**
             * Prijmeni
             * @description Komu se hlásit - příjmení kontaktní osoby
             */
            prijmeni?: string | null;
            /**
             * Titulpredjmenem
             * @description Komu se hlásit - titul před jménem kontaktní osoby
             */
            titulPredJmenem?: string | null;
            /**
             * Titulzajmenem
             * @description Komu se hlásit - titul za jménem kontaktní osoby
             */
            titulZaJmenem?: string | null;
            /**
             * Pozicevespolecnosti
             * @description Komu se hlásit - pozice kontaktní osoby u zaměstnavatele
             */
            poziceVeSpolecnosti?: string | null;
        };
        /** KontaktniPracoviste */
        KontaktniPracoviste: {
            /** Id */
            id: string;
        };
        /** Kraj */
        Kraj: {
            /** Id */
            id: string;
        };
        /** MestskyObvodMestskaCast */
        MestskyObvodMestskaCast: {
            /** Id */
            id: string;
        };
        /** MestskyObvodVPraze */
        MestskyObvodVPraze: {
            /** Id */
            id: string;
        };
        /** MinPozadovaneVzdelani */
        MinPozadovaneVzdelani: {
            /** Id */
            id: string;
        };
        /** MistoVykonuPrace */
        MistoVykonuPrace: {
            typMistaVykonuPrace?: components["schemas"]["TypMistaVykonuPrace"] | null;
            /** @description Obec místa výkonu práce */
            obec?: components["schemas"]["Obec"] | null;
            /**
             * Okresy
             * @description Seznam okresů místa výkonu práce
             */
            okresy?: components["schemas"]["OkresyItem"][] | null;
            /**
             * Adresatext
             * @description Adresa místa výkonu práce, pokud je uvedena volným textem
             */
            adresaText?: string | null;
            /**
             * Pracoviste
             * @description Pracoviště zaměstnavatele pro místo výkonu práce volného místa
             */
            pracoviste?: components["schemas"]["PracovisteItem"][] | null;
        };
        /** Obec */
        Obec: {
            /** Id */
            id: string;
        };
        /** Okres */
        Okres: {
            /** Id */
            id: string;
        };
        /** OkresyItem */
        OkresyItem: {
            /** Id */
            id: string;
        };
        /** PolozkyItem */
        PolozkyItem: {
            /**
             * Portalid
             * @description Jednoznačný identifikátor volného místa na portálu JPŘ PSV
             */
            portalId: number;
            /** Id */
            id: string;
            /**
             * Referencnicislo
             * @description Referenční číslo volného místa
             */
            referencniCislo: string;
            /**
             * Azylant
             * @description Souhlas se zaměstnáním azylantů
             */
            azylant: boolean;
            /**
             * Cizinecmimoeu
             * @description Souhlas se zaměstnáním cizinců jiných států než zemí EU, Lichtenštejnska, Norska a Švýcarska
             */
            cizinecMimoEu: boolean;
            /**
             * Datumvlozeni
             * Format: date-time
             * @description Datum vložení volného místa
             */
            datumVlozeni: string;
            /**
             * Datumzmeny
             * Format: date-time
             * @description Datum poslední změny volného místa
             */
            datumZmeny: string;
            /**
             * Mesicnimzdado
             * @description Mzdové rozpětí - maximální mzda v Kč (měsíční nebo hodinová podle typu mzdy)
             */
            mesicniMzdaDo?: number | null;
            /**
             * Mesicnimzdaod
             * @description Mzdové rozpětí - minimální mzda v Kč (měsíční nebo hodinová podle typu mzdy)
             */
            mesicniMzdaOd?: number | null;
            /**
             * Modrakarta
             * @description Souhlas se zařazením volného místa do centrální evidence VPM pro držitele modré karty
             */
            modraKarta: boolean;
            /**
             * Pocethodintydne
             * @description Minimální počet odpracovaných hodin týdně
             */
            pocetHodinTydne?: number | null;
            /**
             * Pocetmist
             * @description Počet nabízených volných míst v dané profesi
             */
            pocetMist: number;
            /** @description Název požadované profese (dříve profese - doplněk) */
            pozadovanaProfese: components["schemas"]["PozadovanaProfese"];
            /**
             * Statnispravasamosprava
             * @description Místo je určené pro úředníky územních samosprávných celků nebo pro zaměstnance, kteří ve správních úřadech vykonávají státní správu
             */
            statniSpravaSamosprava: boolean;
            /**
             * Terminukoncenipracovnihopomeru
             * @description Datum ukončení pracovního vztahu na dobu určitou
             */
            terminUkonceniPracovnihoPomeru?: string | null;
            /**
             * Terminzahajenipracovnihopomeru
             * Format: date
             * @description Plánovaný nástup: datum, od kdy může uchazeč o zaměstnání nastoupit na uvedené volné místo
             */
            terminZahajeniPracovnihoPomeru: string;
            /**
             * Souhlasagenturyagentura
             * @description Agentury práce - zaměstnanci nebudou agenturou práce přidělováni k zaměstnavateli
             */
            souhlasAgenturyAgentura: boolean;
            /**
             * Souhlasagenturyuzivatel
             * @description Agentury práce - zaměstnanci budou přiděleni k výkonu práce u uživatele
             */
            souhlasAgenturyUzivatel: boolean;
            /** @description Upřesňující informace k volnému místu (dříve poznámka); Jedná se o velmi dlouhý textový řetězec (> 4000 znaků). */
            upresnujiciInformace?: components["schemas"]["UpresnujiciInformace"] | null;
            /**
             * Urladresa
             * @description URL adresa zaměstnavatele, kde lze nalézt další informace k danému volnému místu
             */
            urlAdresa?: string | null;
            /**
             * Zamestnaneckakarta
             * @description Souhlas se zařazením volného místa do centrální evidence VPM pro držitele zaměstnanecké karty
             */
            zamestnaneckaKarta: boolean;
            /**
             * Expirace
             * @description Datum, do kdy bude volné místo zveřejněno na portálu JPŘ PSV
             */
            expirace?: string | null;
            /** @description Požadovaný minimální stupeň vzdělání */
            minPozadovaneVzdelani?: components["schemas"]["MinPozadovaneVzdelani"] | null;
            /** @description Směnnost */
            smennost?: components["schemas"]["Smennost"] | null;
            /** @description Typ mzdy - měsíční nebo hodinová */
            typMzdy?: components["schemas"]["TypMzdy"] | null;
            /** @description Způsob zveřejnění volného místa */
            zverejnovat: components["schemas"]["Zverejnovat"];
            /** @description Místo výkonu práce */
            mistoVykonuPrace: components["schemas"]["MistoVykonuPrace"] | null;
            /** @description Zaměstnavatel */
            zamestnavatel: components["schemas"]["Zamestnavatel"] | null;
            /** @description Požadovaná profese podle číselníku CZ-ISCO */
            profeseCzIsco: components["schemas"]["ProfeseCzIsco"];
            /**
             * Pracovnepravnivztahy
             * @description Typ pracovněprávního vztahu
             */
            pracovnePravniVztahy: components["schemas"]["PracovnePravniVztahyItem"][] | null;
            /**
             * Vhodnostipracovnihomista
             * @description Vhodnost pracovního místa pro typy zaměstnanců
             */
            vhodnostiPracovnihoMista?: components["schemas"]["VhodnostiPracovnihoMistaItem"][] | null;
            /** @description Kontaktní pracoviště ÚP ČR */
            kontaktniPracoviste: components["schemas"]["KontaktniPracoviste"];
            /**
             * Vyhodyvolnehomista
             * @description Nabízené výhody k volnému místu
             */
            vyhodyVolnehoMista?: components["schemas"]["VyhodyVolnehoMistaItem"][] | null;
            /**
             * Pozadovanadovednost
             * @description Požadovaná dovednost pro výkon volného místa
             */
            pozadovanaDovednost?: components["schemas"]["PozadovanaDovednostItem"][] | null;
            /**
             * Pozadovanajazykovaznalost
             * @description Požadovaná jazyková znalost pro výkon volného místa
             */
            pozadovanaJazykovaZnalost?: components["schemas"]["PozadovanaJazykovaZnalostItem"][] | null;
            /**
             * Pozadovanepovolani
             * @description Požadované povolání - praxe v oboru
             */
            pozadovanePovolani?: components["schemas"]["PozadovanePovolaniItem"][] | null;
            /**
             * Pozadovanevzdelani
             * @description Požadované vzdělání podle Klasifikace kmenových oborů vzdělání (KKOV)
             */
            pozadovaneVzdelani?: components["schemas"]["PozadovaneVzdelaniItem"][] | null;
            /** @description První kontakt zájemce se zaměstnavatelem - místo, kde se má hlásit, adresa a další kontakty, kde se má hlásit a osoba, které se má hlásit. */
            prvniKontaktSeZamestnavatelem?: components["schemas"]["PrvniKontaktSeZamestnavatelem"] | null;
        };
        /** PozadovanaDovednostItem */
        PozadovanaDovednostItem: {
            dovednost: components["schemas"]["Dovednost"];
            /** Popis */
            popis?: string | null;
        };
        /** PozadovanaJazykovaZnalostItem */
        PozadovanaJazykovaZnalostItem: {
            urovenZnalosti: components["schemas"]["UrovenZnalosti"];
            jazyk: components["schemas"]["Jazyk"];
            /** Popis */
            popis?: string | null;
        };
        /** PozadovanaProfese */
        PozadovanaProfese: {
            /** Cs */
            cs: string;
        };
        /** PozadovanePovolaniItem */
        PozadovanePovolaniItem: {
            /** Id */
            id: string;
        };
        /** PozadovaneVzdelaniItem */
        PozadovaneVzdelaniItem: {
            /** Id */
            id: string;
        };
        /** PracovisteItem */
        PracovisteItem: {
            /** Email */
            email?: string | null;
            /** Nazev */
            nazev: string;
            /** Telefon */
            telefon?: string | null;
            /** @description Adresa pracoviště */
            adresa?: components["schemas"]["Adresa"] | null;
        };
        /** PracovnePravniVztahyItem */
        PracovnePravniVztahyItem: {
            /** Id */
            id: string;
        };
        /** ProfeseCzIsco */
        ProfeseCzIsco: {
            /** Id */
            id: string;
        };
        /** PrvniKontaktSeZamestnavatelem */
        PrvniKontaktSeZamestnavatelem: {
            komuSeHlasit?: components["schemas"]["KomuSeHlasit"] | null;
            kdeSeHlasit?: components["schemas"]["KdeSeHlasit"] | null;
        };
        /** Smennost */
        Smennost: {
            /** Id */
            id: string;
        };
        /** TypCislaDomovniho */
        TypCislaDomovniho: {
            /** Id */
            id: string;
        };
        /** TypMistaVykonuPrace */
        TypMistaVykonuPrace: {
            /** Id */
            id: string;
        };
        /** TypMzdy */
        TypMzdy: {
            /** Id */
            id: string;
        };
        /** Ulice */
        Ulice: {
            /** Nazev */
            nazev?: string | null;
        };
        /** UpresnujiciInformace */
        UpresnujiciInformace: {
            /** Cs */
            cs: string | null;
        };
        /** UrovenZnalosti */
        UrovenZnalosti: {
            /** Id */
            id: string;
        };
        /** VacancySummary */
        VacancySummary: {
            /** Id */
            id: string;
            /** Profese */
            profese: string;
            /** Zamestnavatel */
            zamestnavatel: string | null;
            /** Mesicni Mzda Od */
            mesicni_mzda_od: number | null;
            /** Mesicni Mzda Do */
            mesicni_mzda_do: number | null;
            /** Typ Mzdy */
            typ_mzdy: string | null;
            /** Kraj */
            kraj: string | null;
            /** Pocet Mist */
            pocet_mist: number;
            /**
             * Datum Vlozeni
             * Format: date
             */
            datum_vlozeni: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VhodnostiPracovnihoMistaItem */
        VhodnostiPracovnihoMistaItem: {
            /** Id */
            id: string;
        };
        /** Vyhoda */
        Vyhoda: {
            /** Id */
            id: string;
        };
        /** VyhodyVolnehoMistaItem */
        VyhodyVolnehoMistaItem: {
            vyhoda: components["schemas"]["Vyhoda"];
            /** Popis */
            popis?: string | null;
        };
        /** Zamestnavatel */
        Zamestnavatel: {
            /** Ico */
            ico?: string | null;
            /** Nazev */
            nazev: string;
        };
        /** Zverejnovat */
        Zverejnovat: {
            /** Id */
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_vacancies_vacancies_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                kraj?: string | null;
                typ_mzdy?: string | null;
                mzda_min?: number | null;
                profese?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacancySummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vacancy_vacancies__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolozkyItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
