# generated by datamodel-codegen:
#   filename:  volna-mista.schema.json
#   timestamp: 2026-07-22T10:02:18+00:00

from __future__ import annotations

from datetime import date
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, Field


class PozadovanaProfese(BaseModel):
    cs: Annotated[str, Field(max_length=300)]


class UpresnujiciInformace(BaseModel):
    cs: str | None


class MinPozadovaneVzdelani(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class Smennost(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class TypMzdy(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class Zverejnovat(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class TypMistaVykonuPrace(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class Obec(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class OkresyItem(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class TypCislaDomovniho(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class Kraj(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class Okres(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class MestskyObvodMestskaCast(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class MestskyObvodVPraze(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class CastObce(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class Ulice(BaseModel):
    nazev: Annotated[str | None, Field(max_length=48)] = None


class Adresa(BaseModel):
    cisloDomovni: int | None = None
    cisloOrientacni: Annotated[str | None, Field(max_length=41)] = None
    dodatekAdresy: Annotated[
        str | None, Field(description='Adresa - dodatek adresy', max_length=250)
    ] = None
    kodAdresnihoMista: int | None = None
    psc: Annotated[str | None, Field(max_length=5)] = None
    typCislaDomovniho: Annotated[
        TypCislaDomovniho | None,
        Field(description='Adresa - typ domovního čísla, typ stavebního objektu'),
    ] = None
    kraj: Kraj | None = None
    okres: Okres | None = None
    obec: Obec | None = None
    mestskyObvodMestskaCast: MestskyObvodMestskaCast | None = None
    mestskyObvodVPraze: MestskyObvodVPraze | None = None
    castObce: CastObce | None = None
    nazevCastiObce: Annotated[str | None, Field(max_length=1024)] = None
    ulice: Ulice | None = None


class PracovisteItem(BaseModel):
    email: Annotated[str | None, Field(max_length=254)] = None
    nazev: Annotated[str, Field(max_length=1024)]
    telefon: Annotated[str | None, Field(max_length=50)] = None
    adresa: Annotated[Adresa | None, Field(description='Adresa pracoviště')] = None


class MistoVykonuPrace(BaseModel):
    typMistaVykonuPrace: TypMistaVykonuPrace | None = None
    obec: Annotated[Obec | None, Field(description='Obec místa výkonu práce')] = None
    okresy: Annotated[
        list[OkresyItem] | None, Field(description='Seznam okresů místa výkonu práce')
    ] = None
    adresaText: Annotated[
        str | None,
        Field(
            description='Adresa místa výkonu práce, pokud je uvedena volným textem',
            max_length=250,
        ),
    ] = None
    pracoviste: Annotated[
        list[PracovisteItem] | None,
        Field(
            description='Pracoviště zaměstnavatele pro místo výkonu práce volného místa'
        ),
    ] = None


class Zamestnavatel(BaseModel):
    ico: Annotated[str | None, Field(max_length=8)] = None
    nazev: Annotated[str, Field(max_length=500)]


class ProfeseCzIsco(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class PracovnePravniVztahyItem(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class VhodnostiPracovnihoMistaItem(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class KontaktniPracoviste(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class Vyhoda(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class VyhodyVolnehoMistaItem(BaseModel):
    vyhoda: Vyhoda
    popis: Annotated[str | None, Field(max_length=512)] = None


class Dovednost(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class PozadovanaDovednostItem(BaseModel):
    dovednost: Dovednost
    popis: Annotated[str | None, Field(max_length=2048)] = None


class UrovenZnalosti(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class Jazyk(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class PozadovanaJazykovaZnalostItem(BaseModel):
    urovenZnalosti: UrovenZnalosti
    jazyk: Jazyk
    popis: Annotated[str | None, Field(max_length=2048)] = None


class PozadovanePovolaniItem(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class PozadovaneVzdelaniItem(BaseModel):
    id: Annotated[str, Field(max_length=129)]


class KomuSeHlasit(BaseModel):
    email: Annotated[
        str | None,
        Field(
            description='Kontaktovat zaměstnavatele e-mailem - e-mail', max_length=254
        ),
    ] = None
    telefon: Annotated[
        str | None,
        Field(
            description='Kontaktovat zaměstnavatele telefonem - telefon', max_length=50
        ),
    ] = None
    jmeno: Annotated[
        str | None,
        Field(description='Komu se hlásit - jméno kontaktní osoby', max_length=100),
    ] = None
    prijmeni: Annotated[
        str | None,
        Field(description='Komu se hlásit - příjmení kontaktní osoby', max_length=100),
    ] = None
    titulPredJmenem: Annotated[
        str | None,
        Field(
            description='Komu se hlásit - titul před jménem kontaktní osoby',
            max_length=35,
        ),
    ] = None
    titulZaJmenem: Annotated[
        str | None,
        Field(
            description='Komu se hlásit - titul za jménem kontaktní osoby',
            max_length=10,
        ),
    ] = None
    poziceVeSpolecnosti: Annotated[
        str | None,
        Field(
            description='Komu se hlásit - pozice kontaktní osoby u zaměstnavatele',
            max_length=250,
        ),
    ] = None


class Adresa1(BaseModel):
    cisloDomovni: int | None = None
    cisloOrientacni: Annotated[str | None, Field(max_length=41)] = None
    dodatekAdresy: Annotated[
        str | None, Field(description='Adresa - dodatek adresy', max_length=250)
    ] = None
    kodAdresnihoMista: int | None = None
    psc: Annotated[str | None, Field(max_length=5)] = None
    typCislaDomovniho: Annotated[
        TypCislaDomovniho | None,
        Field(description='Adresa - typ domovního čísla, typ stavebního objektu'),
    ] = None
    kraj: Kraj | None = None
    okres: Okres | None = None
    obec: Obec | None = None
    mestskyObvodMestskaCast: MestskyObvodMestskaCast | None = None
    mestskyObvodVPraze: MestskyObvodVPraze | None = None
    castObce: CastObce | None = None
    nazevCastiObce: Annotated[str | None, Field(max_length=1024)] = None
    ulice: Ulice | None = None


class KdeSeHlasit(BaseModel):
    email: Annotated[
        str | None,
        Field(
            description='Kontaktovat zaměstnavatele e-mailem - e-mail', max_length=254
        ),
    ] = None
    telefon: Annotated[
        str | None,
        Field(
            description='Kontaktovat zaměstnavatele telefonem - telefon', max_length=50
        ),
    ] = None
    mistoKontaktu: Annotated[
        str | None,
        Field(
            description='Kontaktovat zaměstnavatele osobně - místo kontaktu',
            max_length=4000,
        ),
    ] = None
    adresa: Annotated[Adresa1 | None, Field(description='Adresa kontaktu')] = None


class PrvniKontaktSeZamestnavatelem(BaseModel):
    komuSeHlasit: KomuSeHlasit | None = None
    kdeSeHlasit: KdeSeHlasit | None = None


class PolozkyItem(BaseModel):
    portalId: Annotated[
        int,
        Field(description='Jednoznačný identifikátor volného místa na portálu JPŘ PSV'),
    ]
    id: Annotated[str, Field(max_length=129)]
    referencniCislo: Annotated[
        str, Field(description='Referenční číslo volného místa', max_length=17)
    ]
    azylant: Annotated[bool, Field(description='Souhlas se zaměstnáním azylantů')]
    cizinecMimoEu: Annotated[
        bool,
        Field(
            description='Souhlas se zaměstnáním cizinců jiných států než zemí EU, Lichtenštejnska, Norska a Švýcarska'
        ),
    ]
    datumVlozeni: Annotated[
        AwareDatetime, Field(description='Datum vložení volného místa')
    ]
    datumZmeny: Annotated[
        AwareDatetime, Field(description='Datum poslední změny volného místa')
    ]
    mesicniMzdaDo: Annotated[
        float | None,
        Field(
            description='Mzdové rozpětí - maximální mzda v Kč (měsíční nebo hodinová podle typu mzdy)'
        ),
    ] = None
    mesicniMzdaOd: Annotated[
        float | None,
        Field(
            description='Mzdové rozpětí - minimální mzda v Kč (měsíční nebo hodinová podle typu mzdy)'
        ),
    ] = None
    modraKarta: Annotated[
        bool,
        Field(
            description='Souhlas se zařazením volného místa do centrální evidence VPM pro držitele modré karty'
        ),
    ]
    pocetHodinTydne: Annotated[
        float | None, Field(description='Minimální počet odpracovaných hodin týdně')
    ] = None
    pocetMist: Annotated[
        int, Field(description='Počet nabízených volných míst v dané profesi')
    ]
    pozadovanaProfese: Annotated[
        PozadovanaProfese,
        Field(description='Název požadované profese (dříve profese - doplněk)'),
    ]
    statniSpravaSamosprava: Annotated[
        bool,
        Field(
            description='Místo je určené pro úředníky územních samosprávných celků nebo pro zaměstnance, kteří ve správních úřadech vykonávají státní správu'
        ),
    ]
    terminUkonceniPracovnihoPomeru: Annotated[
        date | None,
        Field(description='Datum ukončení pracovního vztahu na dobu určitou'),
    ] = None
    terminZahajeniPracovnihoPomeru: Annotated[
        date,
        Field(
            description='Plánovaný nástup: datum, od kdy může uchazeč o zaměstnání nastoupit na uvedené volné místo'
        ),
    ]
    souhlasAgenturyAgentura: Annotated[
        bool,
        Field(
            description='Agentury práce - zaměstnanci nebudou agenturou práce přidělováni k zaměstnavateli'
        ),
    ]
    souhlasAgenturyUzivatel: Annotated[
        bool,
        Field(
            description='Agentury práce - zaměstnanci budou přiděleni k výkonu práce u uživatele'
        ),
    ]
    upresnujiciInformace: Annotated[
        UpresnujiciInformace | None,
        Field(
            description='Upřesňující informace k volnému místu (dříve poznámka); Jedná se o velmi dlouhý textový řetězec (> 4000 znaků).'
        ),
    ] = None
    urlAdresa: Annotated[
        str | None,
        Field(
            description='URL adresa zaměstnavatele, kde lze nalézt další informace k danému volnému místu',
            max_length=2048,
        ),
    ] = None
    zamestnaneckaKarta: Annotated[
        bool,
        Field(
            description='Souhlas se zařazením volného místa do centrální evidence VPM pro držitele zaměstnanecké karty'
        ),
    ]
    expirace: Annotated[
        date | None,
        Field(
            description='Datum, do kdy bude volné místo zveřejněno na portálu JPŘ PSV'
        ),
    ] = None
    minPozadovaneVzdelani: Annotated[
        MinPozadovaneVzdelani | None,
        Field(description='Požadovaný minimální stupeň vzdělání'),
    ] = None
    smennost: Annotated[Smennost | None, Field(description='Směnnost')] = None
    typMzdy: Annotated[
        TypMzdy | None, Field(description='Typ mzdy - měsíční nebo hodinová')
    ] = None
    zverejnovat: Annotated[
        Zverejnovat, Field(description='Způsob zveřejnění volného místa')
    ]
    mistoVykonuPrace: Annotated[
        MistoVykonuPrace | None, Field(description='Místo výkonu práce')
    ]
    zamestnavatel: Annotated[Zamestnavatel | None, Field(description='Zaměstnavatel')]
    profeseCzIsco: Annotated[
        ProfeseCzIsco, Field(description='Požadovaná profese podle číselníku CZ-ISCO')
    ]
    pracovnePravniVztahy: Annotated[
        list[PracovnePravniVztahyItem] | None,
        Field(description='Typ pracovněprávního vztahu'),
    ]
    vhodnostiPracovnihoMista: Annotated[
        list[VhodnostiPracovnihoMistaItem] | None,
        Field(description='Vhodnost pracovního místa pro typy zaměstnanců'),
    ] = None
    kontaktniPracoviste: Annotated[
        KontaktniPracoviste, Field(description='Kontaktní pracoviště ÚP ČR')
    ]
    vyhodyVolnehoMista: Annotated[
        list[VyhodyVolnehoMistaItem] | None,
        Field(description='Nabízené výhody k volnému místu'),
    ] = None
    pozadovanaDovednost: Annotated[
        list[PozadovanaDovednostItem] | None,
        Field(description='Požadovaná dovednost pro výkon volného místa'),
    ] = None
    pozadovanaJazykovaZnalost: Annotated[
        list[PozadovanaJazykovaZnalostItem] | None,
        Field(description='Požadovaná jazyková znalost pro výkon volného místa'),
    ] = None
    pozadovanePovolani: Annotated[
        list[PozadovanePovolaniItem] | None,
        Field(description='Požadované povolání - praxe v oboru'),
    ] = None
    pozadovaneVzdelani: Annotated[
        list[PozadovaneVzdelaniItem] | None,
        Field(
            description='Požadované vzdělání podle Klasifikace kmenových oborů vzdělání (KKOV)'
        ),
    ] = None
    prvniKontaktSeZamestnavatelem: Annotated[
        PrvniKontaktSeZamestnavatelem | None,
        Field(
            description='První kontakt zájemce se zaměstnavatelem - místo, kde se má hlásit, adresa a další kontakty, kde se má hlásit a osoba, které se má hlásit.'
        ),
    ] = None


class VolnaMista(BaseModel):
    polozky: list[PolozkyItem] | None = None
